# curl -X POST -F "file=@/path/to/file.jpg" http://localhost:8080/upload

POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.jpg"

< example/file.jpg
--WebAppBoundary--

###

POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.pdf"

< example/file.pdf
--WebAppBoundary--

###

POST http://localhost:8080/file
Content-Type: Application/json

{
  "token": "a6f85c72652aa0173bb4b30512f1ccc142eea7aa3e959a5ce38e25ed45268e55"
}

###

